### ISSUE TITLE
More experimental information on C4 dataset

### ISSUE THREAD

**Issue by lxl910915** [google-research/text-to-text-transfer-transformer#16]
In your [paper](https://arxiv.org/pdf/1910.10683.pdf), table 9 gives the results on different number os tokens and figure 6 gives the coresponding loss. Can you provide the experimental information about the TPU numbers and training time ? Thank you!

**Comment by craffel** [comment]
Hi, all of the results in the table had the same amount of training time and were trained on the same hardware. Note that the model was pre-trained on the same number of tokens for each of those experiments, the dataset itself was just artificially limited in size so that it was repeated over the course of pre-training. The training time will scale with the TPU size up to about a v3-32, at which point the model becomes input bound.

**Comment by lxl910915** [comment]
> Hi, all of the results in the table had the same amount of training time and were trained on the same hardware. Note that the model was pre-trained on the same number of tokens for each of those experiments, the dataset itself was just artificially limited in size so that it was repeated over the course of pre-training. The training time will scale with the TPU size up to about a v3-32, at which point the model becomes input bound.

Can you provide the details about training time and hardware？

**Comment by craffel** [comment]
The training time/cost for those experiments is the same as the baseline experimental setup. Most of our experiments were run on TPU v3-8 accelerators (referred to simply as a "Cloud TPU v3" in the Cloud docs).

**Comment by lxl910915** [comment]
Get it!
