### ISSUE TITLE
how to preprocess text for pretrain?

### ISSUE THREAD

**Issue by LiweiPeng** [google-research/text-to-text-transfer-transformer#211]
I'd like to use T5 model to pretrain my own text from scratch. Assuming my raw text is formatted in the same format like what WikiExtractor.py does for wikipedia text, can you share instructions or scripts on how to preprocess my own text for t5? Something like what BERT did (https://github.com/google-research/bert/blob/master/create_pretraining_data.py). Thanks.

**Comment by matchlesswei** [comment]
I think the preprocessing part should be similar as in the example notebook: https://github.com/google-research/text-to-text-transfer-transformer/blob/master/notebooks/t5-trivia.ipynb

Just you need to add your own operative_config.gin(https://github.com/google-research/text-to-text-transfer-transformer/issues/30) and use model.train(mixture_or_task_name=MIXTURE_NAME, steps=TRAIN_STEPS)

**Comment by mainakmanna** [comment]
As mentioned already, `t5-trivia` ipython notebook used pre-processing. To be very specific look at the `trivia_preprocessor` function. Once you have a `tf.data.Dataset`, you can now pass it to the `text_preprocessor` which can do custom processing as needed in your case. For example in the case of the `trivia_preprocessor` function dataset is converted to the text-to-text format. Also, the texts are lowercased and the quotes are removed. 

@matchlesswei mentioned, the issue discussed an important step of using the gin file, otherwise, you will run into error. Before calling `model.train()` one can load a gin file like this. (On this example, which is taken from that issue, we are using `gin` file of the base model).
```
import gin
    with gin.unlock_config():
      gin.parse_config_file("gs://t5-data/pretrained_models/base/operative_config.gin")
```

You can change some parameters using `gin.bind_parameter()`. 

_(Correct me if I missed something or mentioned something wrong)._

**Comment by LiweiPeng** [comment]
Thanks for the updates. I'll use the example code and gin file.

**Comment by ashispapu** [comment]
@LiweiPeng Hey Did you try to pre train T5 ? if yes, could you share the details. 
Thanks.
