### ISSUE TITLE
Targets for Span de-noising is incorrect 

### ISSUE THREAD

**Issue by agemagician** [google-research/text-to-text-transfer-transformer#249]
Hello,

I am training a new unsupervised task, and when I use "iid_noise_mask" the input and targets are correct. The inputs and targets are identical and have the same length and the only change is the tokens masking.

However, when I use "random_spans_noise_mask" the inputs are correct but the targets don't respect inputs maximum length.

Original Sample:
**M A S N T V S A Q G G S N R P V R D F S N I Q D V A Q F L L F D P** I W N E Q P G S I V P W K M N R E Q A L A E R Y P E L Q T S E P S E D Y S G P V E S L E L L P L E I K L D I M Q Y L S W E Q I S W C K H P W L W T R W Y K D N V V R V S A I T F E D F Q R E Y A F P E K I Q E I H F T D T R A E E I K A I L E T T P N V T R L V I R R I D D M N Y N T H G D L G L D D L E F L T H L M V E D A C G F T D F W A P S L T H L T I K N L D M H P R W F G P V M D G I K S M Q S T L K Y L Y I F E T Y G V N K P F V Q W C T D N I E T F Y C T N S Y R Y E N V P R P I Y V W V L F Q E D E W H G Y R V E D N K F H R R Y M Y S T I L H K R D T D W V E N N P L K T P A Q V E M Y K F L L R I S Q L N R D G T G Y E S D S D P E N E H F D D E S F S S G E E D S S D E D D P T W A P D S D D S D W E T E T E E E P S V A A R I L E K G K L T I T N L M K S L G F K P K P K K I Q S I D R Y F C S L D S N Y N S E D E D F E Y D S D S E D D D S D S E D D C

Inputs features:
M A S ⁇ S A Q G G S N R P V R D F S N I Q D V A Q F L L F D P

Targets features:
⁇ N T V ⁇ T ⁇ I K L D I ⁇ Y ⁇ R ⁇ M N ⁇ A P S L T H L T ⁇ P I

My expectation that the target's features should shorter than the input's features.
i.e:
Inputs features:
M A S ⁇ S A Q G G S N R P V R D F S N I Q D V A Q F L L F D P

Targets features:
⁇ N T V

My minimal code is:
```
SEQ_LEN = 32

def token_noise(dataset, output_features, **unused_kwargs):
  return denoise(dataset, output_features,
                 noise_density = 0.15, 
                 noise_mask_fn = random_spans_noise_mask,
                 inputs_fn = noise_span_to_unique_sentinel, 
                 targets_fn=nonnoise_span_to_unique_sentinel)

t5.data.TaskRegistry.remove("unsupervised_denoising_task")
t5.data.TaskRegistry.add(
    "unsupervised_denoising_task",
    dataset_fn=dataset_fn,
    splits=["train", "validation"],
    text_preprocessor=[text_preprocessor],
    token_preprocessor=[token_noise],
    output_features=t5.data.Feature(vocabulary=vocab,add_eos=True),
    metric_fns=[t5.evaluation.metrics.accuracy],
    num_input_examples=num_examples
)
task = t5.data.TaskRegistry.get("unsupervised_denoising_task")
ds = task.get_dataset(split="train", sequence_length={"inputs": SEQ_LEN, "targets": SEQ_LEN})

```

I also tried to replace my call to the denoise function with importing "span.gin" but the output is the same.

Any idea how to fix this issue ?

**Comment by adarob** [comment]
@nshazeer PTAL

**Comment by nshazeer** [comment]
Since noise_density=0.15, the targets are necessarily shorter than the inputs, since the targets consist of the tokens that are selected to be "noise", along with sentinel tokens.   If you want the targets to be the same length as the inputs, then you need noise_density=0.5 .       Also, span.gin contains settings that set the target sequence length automatically based on the input sequence length and the noise density.  If you want equal length inputs and targets, then continue to use span.gin, but just override noise_density with 0.5 .

**Comment by agemagician** [comment]
Hi @nshazeer, thanks for your reply.
But you got the opposite of what I am trying to achieve. 

I am excepting that the targets will be shorter than the inputs given that the noise_density=0.15. However, this is not the case. The inputs and targets have the same length.
The produced targets always have the same length as the inputs despite the noise_density=0.15.

**Comment by agemagician** [comment]
Thanks a lot for your help, I think I was able to overcome the problem by using split_tokens along with denoise.
I will close the issue for now.

**Comment by nshazeer** [comment]
Oh sorry - I didn't read your question correctly.   If you look at span.gin, you will see that there is a lot of magic that computes the target sequence length based on the macros inputs_length, noise_density, and mean_noise_span_length:

targets_length = @preprocessors.random_spans_targets_length()
preprocessors.random_spans_helper.inputs_length = %inputs_length
preprocessors.random_spans_helper.noise_density = %noise_density
preprocessors.random_spans_helper.mean_noise_span_length = %mean_noise_span_length
preprocessors.random_spans_helper.extra_tokens_per_span_inputs = 1
preprocessors.random_spans_helper.extra_tokens_per_span_targets = 1
utils.run.sequence_length = {"inputs": %inputs_length, "targets": %targets_length}

You will need to either use this, call the same functions, or otherwise figure out the correct value of targets_length so as to set it explicitly.

**Comment by agemagician** [comment]
@nshazeer  Thanks a lot for the explanation. I will stick with the gin file, since it is working as excepted.
