### ISSUE TITLE
Some german uppercase characters like "Ö" are missing from the vocabulary

### ISSUE THREAD

**Issue by marton-avrios** [google-research/text-to-text-transfer-transformer#389]
"ü" is 1272, "Ü" is 14858, "ö" is 1872 but "Ö" is 2 (unknown). Is that possible or I messed up something?

**Comment by craffel** [comment]
Hi, this must simply be because SentencePiece learns its vocabulary and decided that it could compress text better if it used one of its IDs for a different text sequence than Ö. Unfortunately SentencePiece added the byte fallback mode after we made our vocabulary. We may release models that have better coverage/byte fallback soon.
