### ISSUE TITLE
Mistakes in T5 SentencePiece Tokenizer

### ISSUE THREAD

**Issue by misrasaurabh1** [google-research/text-to-text-transfer-transformer#390]
T5 Tokenizer is based out of SentencePiece and in sentencepiece whitespace is treated as a basic symbol. But it seems like the tokenizer just ignores more than one whitespace (including space, newline and tab)
Consider all the following examples tokenize to the same thing.
```
>>> tokenizer = SentencePieceVocabulary("/path/to/vocabs_cc_all.32000_sentencepiece.model")
>>> tokenizer.encode("Hi there I'm good")
[2018, 132, 27, 31, 51, 207]
>>> tokenizer.encode("Hi there     I'm good")
[2018, 132, 27, 31, 51, 207]
>>> tokenizer.encode("Hi there    I'm good\n")
[2018, 132, 27, 31, 51, 207]
>>> tokenizer.encode("Hi there \n  \t   I'm good\n")
[2018, 132, 27, 31, 51, 207]
```

T5 tokenizer also messes up this particular sequence
```
>>> tokenizer.decode(tokenizer.encode("My phone number is  1-${phone.number}")))
'My phone number is 1-$ ⁇ phone.number ⁇ '
```
It adds this weird ⁇ symbol, failing to encode the `{` symbol.
This is causing problems while deploying the T5 model.

**Comment by craffel** [comment]
> it seems like the tokenizer just ignores more than one whitespace (including space, newline and tab)

This is a standard feature of SentencePiece.

> failing to encode the { symbol.

{ is OOV because we intentionally removed any pages with { or } from C4 to avoid pre-training on anything other than natural language. So, it gets encoded to ??. SentencePiece has a byte fallback feature but it was not available when we trained our sentencepiece model.

You can create your own Vocabulary class based on something other than SentencePiece, and train your own vocabulary, and pre-train your own model, if you would like to avoid either of the above.
