### ISSUE TITLE
[T5 v1.1] PreTrained Tokenizer Files

### ISSUE THREAD

**Issue by patrickvonplaten** [google-research/text-to-text-transfer-transformer#521]
Hey @craffel , 

Sorry to annoy you again. Do the new T5 v1.1 models: https://github.com/google-research/text-to-text-transfer-transformer/blob/master/released_checkpoints.md use the same pretrained tokenizers as the original T5 models?

**Comment by craffel** [comment]
Yes. (note that mT5, which is based on T5.1.1, of course uses a different vocab)

**Comment by shenfe** [comment]
Same question with @patrickvonplaten , because I have tried many times to finetune T5.1.1 on some tasks, but got very lower performance than T5.1.0.

I was using the same pretrained sentencepiece model to tokenize for both T5.1.0 and T5.1.1. So I have some doubt about if the two versions have different token->id mappings, which could result in the difference during training.

**Comment by Arij-Aladel** [comment]
I am sorry for this question I am not an expert here, but this question is in my mind for a while. I understand the difference between the pre-rained T5 models is the number of layers and consequently the number of parameters. But what is the difference then between the pre-trained tokenizers? I mean All models are pre-trained on c4, if the tokenizer is also trained on c4 corpus then why load the tokenizer with different names? Is the pre-trained tokenizer is the same for all models but when loading the pre-trained tokenizer we refer to the config of the pre-trained model which inside has the path to the same pre-trained tokenizer?
