### ISSUE TITLE
adding prefix to targets instead of inputs

### ISSUE THREAD

**Issue by marton-avrios** [google-research/text-to-text-transfer-transformer#588]
I wander if it's possible to train t5 for a scenario where you always feed the same input but depending on how the target sequence starts it outputs different things? So conditional text generation conditioned on encoder output and a prefix. Basic way to do it would be to just simply remove prefix from input, add it to target and train the model. When decoding with the trained model it would work well since I can specify partial sequences for `sample_autoregressive`. But what about during training? The model would try to learn to output the prefix too which is basically random. Only after the prefix can it learn something.

Example:
input: "Hello world!", output: "translate to german: \<the german translation\>"
input: "Hello world!", output: "translate to french: \<the french translation\>"

**Comment by craffel** [comment]
Hi, this would be simple to implement in our codebase - you just need to implement a preprocessor that appends the prefix to the targets rather than the inputs. Basically do the tf.strings.join to targets rather than inputs here:
https://github.com/google-research/text-to-text-transfer-transformer/blob/master/t5/data/preprocessors.py#L95
