### ISSUE TITLE
Ax-b and Ax-g performance of T5

### ISSUE THREAD

**Issue by juliahane** [google-research/text-to-text-transfer-transformer#659]
Hi
I see very high SCORE on these datasets on the benchmark system, could you elaborate how you compute the score on these datasets? is this zero-shot in your case? so training on GLUE and then transfer to these datasets? thanks

**Comment by craffel** [comment]
Hi, typical practice (followed by us) is to use RTE checkpoint to evaluate performance on these datasets.

**Comment by juliahane** [comment]
Hi
thank you, do you mind elaborating why RTE versus MNLI? and if you know of
any reference on this, it would be awesome to know
thanks

**Comment by craffel** [comment]
IIRC it's because AX-* only use the entailment/contradiction labels (like RTE) and not the additional neutral label (like MNLI). I don't remember where we learned this was common practice. If you ask on the glue discussion group someone may know. Usually people use MNLI for intermediate-task or multi-task training for RTE, so you probably get the MNLI benefits either way.

**Comment by juliahane** [comment]
thanks a lot

**Comment by yardenTal1** [comment]
Hi,
I reopen thin post again. hope that it's ok.
I wand to evaluate performance on Ax-g dataset.
I tried to do this in two different ways - 
1. fine-tuned the t5 google checkpoint (the version with supervised training) first with MNLI and then with RTE
2. fine-tuned the t5 google checkpoint (the version with supervised training) only with RTE

Incomprehensibly I get much less good results in AXG after fine tuning than before.

I would really happy your help,
Thanks,
Yarden.

@craffel
