### ISSUE TITLE
Colab crashes when running t5-trivia

### ISSUE THREAD

**Issue by wehrlean** [google-research/text-to-text-transfer-transformer#937]
**Describe the bug**
Colab is crashing if you try to run the t5-trivia. The setup doesn't work since yesterday. Colab crashes with no more error information

**To Reproduce**
1. Run the t5-trivia notebook

**Additional context**
I think it has something to do with` import tensorflow_gcs_config` but i am not sure

**Comment by wehrlean** [comment]
Seems there is a problem with the new version of Tensorflow(_gcs_config). 
Going back to version 2.6:
`!pip install -q tensorflow==2.6.2`
`!pip install -q tensorflow-gcs-config==2.6.0`

**Comment by adarob** [comment]
Thanks for raising this and figuring out a workaround!

It seems that the issue is that tensorflow-text is still on v2.6, which causes tensorflow to be downgraded from 2.7 to 2.6 as well. However, this means the installed tensorflow version is 2.6 and tensorflow-gcs-config is still 2.7, resulting in the crash.

We may want to push your workaround temporarily, dpeending on how long it will be before tf-text upgrades. Checking with @broken.

**Comment by wehrlean** [comment]
tensorflow-text updated to v2.7. No more workaround needed.

**Comment by wehrlean** [comment]
tensorflow-text updated to v2.7. No more workaround needed.

**Comment by adarob** [comment]
Excellent, thanks for checking back in!
