### ISSUE TITLE
About token preprocessors defined in span_3_15_u_u.gin

### ISSUE THREAD

**Issue by ogis-uno** [google-research/text-to-text-transfer-transformer#95]
Hi, I have a question about token preprocessors defined in span_3_15_u_u.gin.

I have trained a Encoder-Decoder model with span_3_15_u_u.gin. 
In span_3_15_u_u.gin(actually span.gin), the preprocessors are defined as follows,
```
preprocessors.unsupervised.preprocessors = [
@preprocessors.select_random_chunk,
@preprocessors.reduce_concat_tokens,
@preprocessors.split_tokens,
@preprocessors.denoise,
]
```

To check the details of preprocessing, I have manually mimicked the preprocessing defined in span_3_15_u_u.gin as follows,

```
import tensorflow as tf
tf.compat.v1.enable_eager_execution()
from t5.data.preprocessors import select_random_chunk, reduce_concat_tokens, split_tokens

def print_and_copy_data(name, dataset):
  print("\n### %s ###" % name)
  data = []
  for example in dataset:
    data.append(example['targets'].numpy())
    print(" 'targets' : %s" % (data[-1]))
  return tf.data.Dataset.from_tensor_slices({'targets': data})

dataset = tf.data.Dataset.from_tensor_slices({'targets': [
              [10, 11, 12, 13, 14, 15, 16, 17, 18, 19], 
              [20, 21, 22, 23, 24, 25, 26, 27, 28, 29], 
              [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]]}) 
dataset = print_and_copy_data("Tokenized sentences.", dataset)

dataset = select_random_chunk(dataset, max_length=5)
dataset = print_and_copy_data("select_random_chunk()", dataset)

dataset = reduce_concat_tokens(dataset, batch_size=3)
dataset = print_and_copy_data("reduce_concat_tokens()", dataset)

dataset = split_tokens(dataset, min_tokens_per_segment=None, max_tokens_per_segment=3)
print_and_copy_data("split_tokens()", dataset)
```
And output is,
```
### Tokenized sentences. ###
 'targets' : [10 11 12 13 14 15 16 17 18 19]
 'targets' : [20 21 22 23 24 25 26 27 28 29]
 'targets' : [30 31 32 33 34 35 36 37 38 39]

### select_random_chunk() ###
 'targets' : [15 16 17 18 19]
 'targets' : [25 26 27 28 29]
 'targets' : [30 31 32 33 34]

### reduce_concat_tokens() ###
 'targets' : [15 16 17 18 19 25 26 27 28 29 30 31 32 33 34]

### split_tokens() ###
 'targets' : [15 16 17]
 'targets' : [18 19 25]
 'targets' : [26 27 28]
 'targets' : [29 30 31]
 'targets' : [32 33 34]
``` 
My question is :

After split_tokens(), `[18 19 25]` and `[29 30 31]` spanned the two original sentences,
but have no signals indicate the original sentence border. 
And does this not confuse the Transformers?

T5 paper says 

> Whenever possible, we “pack” multiple sequences into each entry of the batch[10] 

and Note[10] references `pack_examples()` of tensor2tensor. I think this note is corresponded to `mesh_tensorflow.transformer.dataset.pack_dataset()` which is called from `t5.models.mesh_transformer.mesh_train_dataset_fn()`.

In `pack_dataset()`, `'inputs_segmentations'` feature is generated and passed as `encoder_sequence_id` of transformer's call_simple() correctly in `mesh_tensorflow.transformer.utils.logits_and_loss()`.

But before this point, `reduce_concat_tokens()` and `split_tokens()` are already applied and sentence borders are evaporated. so I think.
 
Or I had a misunderstanding / missed something in mimicking?

**Comment by craffel** [comment]
Hi, note that
1. For pre-training, `select_random_chunk` uses `max_length = 65536`
1. If the input to select_random_chunk is shorter than `max_length`, it won't be truncated
1. Input sequence length in the batch is 512

Most input documents are less than 65536 tokens long, so it is rare that the output of `select_random_chunk` will end mid-sentence. For shorter documents, note that the document will always end at the end of a sentence because of the way we create C4. But, even shorter documents tend to be longer than 512 tokens. So, the most likely thing is that a length-512 preprocessed sequence in a batch all comes from one document. The next most likely thing is that a sequence changes documents after a sentence, since it contains info from two documents which were not truncated by `select_random_chunk`. The least likely thing is that a sequence abruptly changes documents mid-sentence because it was truncated by `select_random_chunk`. We are not too worried about confusing the Transformer in the latter two cases since a) they are quite rare and b) it is probably not too confusing to change topics quickly (it happens often in documents, too, since web pages can contain diverse content).

Hope this makes sense.
